version: '3'

services:
  kiwi4:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SESSION_SECRET=change_me_in_production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped 